Updated readme
trackier/flutter-sdk pull request #5
Opened 2022-07-08 12:36 UTC by IloveJavaa

2022-07-11 06:35 UTC, arpit9616 requested changes
SDK Signing section is missing.

2022-07-11 07:03 UTC, Hemant-Mann approved these changes

2022-07-11 07:04 UTC, Hemant-Mann commented
Apart from @arpit9616 comment it looks good

2022-07-11 12:05 UTC, arpit9616 requested changes
Update pod dependencies section is present, but the index navigation is broken for the same.

2022-07-12 06:02 UTC, arpit9616 approved these changes

2022-07-12 06:02 UTC, merged